### PR TITLE
Fix recipe conflict between Item and Fluid Storage Parts

### LINKED ISSUE #49: [1.12.1-2.0.1.6] Extended item storage parts use fluid parts for crafting components
The 256k Item Storage Part's crafting recipe requires the highest tier of *Fluid* Storage Part in base Refined Storage.

Also, just a suggestion, but configuration to disable the extra storage disks would be nice.

### PR DESCRIPTION
**Pull request by Leo40Git**
Closes #49.

### CODE REVIEW

**Comment by modmuss50** [comment]
Looks good, just not sure why you needed to change the Gradle stuff? Undo that and It should be good to merge.

**Comment by Leo40Git** [comment]
I couldn't get Eclipse's Gradle integration to work, so I screwed around with the Gradle files. Still couldn't get it to work, although I did manage to test it (though Refined Storage had no localization for some reason).
Now undoing.

**Comment by drcrazy** [comment]
as for eclipse:
1) gradlew setupdecompworkspace
2) gradlew eclipse 
Both from command line
Then import gradle project and set JDK manually

**Comment by Leo40Git** [comment]
Gave me an "Invalid project description" error when I tried that.

**Comment by modmuss50** [comment]
Thanks for that

**Comment by drcrazy** [comment]
c:\_Docs\mc1.12\RebornStorage>gradlew eclipse
This mapping 'snapshot_20170624' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-ac7f579
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:extractMcpMappings SKIPPED
:deobfCompileDeobfDepTask0 SKIPPED
:deobfCompileDeobfDepTask1 SKIPPED
:deobfCompileRemapDepSourcesTask2 SKIPPED
:deobfCompileDummyTask
:deobfProvidedDummyTask
:eclipseClasspath
:eclipseJdt
:eclipseProject
:getVersionJson
:extractNatives SKIPPED
:extractUserdev UP-TO-DATE
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 783/1281   61%
:makeStart
:makeEclipseCleanRunClient
:makeEclipseCleanRunServer
:eclipse

BUILD SUCCESSFUL

**Comment by Leo40Git** [comment]
It gave me that error when I tried to import the Gradle project and when I tried to add a Gradle nature to the Java project.

**Pull request merged**
